version: '3.8'

#TODO: edit and fix

services:

  client:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3003:3003"

